### ISSUE TITLE
Current fuzzing failures

### ISSUE THREAD

**Issue by apollo13** [django/django-fuzzers#1]
I am somewhat unsure how to fix this error:
```
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/fuzzer-utils.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/fuzzer-utils.zip or
Step #5:         /corpus/fuzzer-utils.zip.zip, and cannot find /corpus/fuzzer-utils.zip.ZIP, period.
Step #5: Failed to unpack the corpus for fuzzer-utils. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image django
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage django
Step #5: python infra/helper.py coverage django
Step #5: ********************************************************************************
Finished Step #5
ERROR
ERROR: build step 5 "gcr.io/oss-fuzz-base/base-runner" failed: step exited with non-zero status: 1
```

@guidovranken Do you have any ideas on how to fix this, or whom to ask for help in such situations?

**Comment by guidovranken** [comment]
I ran into this issue before with another fuzzer https://github.com/google/oss-fuzz/issues/3224 and it was resolved after some time..

In the case of Django I can disable the coverage build. The coverage build creates reports like: https://storage.googleapis.com/oss-fuzz-coverage/django/reports/20210601/linux/report.html

Usually it's useful to have a coverage report, so you can see which code the fuzzer is accessing, but it only works on the C level, not the Python level, so in Django's case I might as well disable it.

**Comment by apollo13** [comment]
> so in Django's case I might as well disable it.

That would be great :+1:

**Comment by apollo13** [comment]
@guidovranken If you do not have time to disable the coverage report, can you recommend where we should look around & ask?

**Comment by guidovranken** [comment]
I did look at this a while ago but couldn't find a way to disable coverage reports after all.. Would you mind creating an issue in https://github.com/google/oss-fuzz/issues? The folks from Google will help you.

**Comment by apollo13** [comment]
Closing in favor of https://github.com/google/oss-fuzz/issues/6937
